Repository SilviaPabon/vacational_website, pull requests merged in 2021-12, with the labels that each got.

#1 Navbar
  src/public/scripts/navbar.js
  src/public/styles/base/_globals.scss
  src/public/styles/components/_components.scss
  src/public/styles/layouts/_navbar.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/vendors/_normalize.scss
  src/views/layouts/main.hbs
Labels: section/component finished 👣

#3 Fix navbar z-index 🐛
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
Labels: bug

#4 Plan details page initial version.
  src/controllers/plans_controller.js
  src/index.js
  src/libs/handlebarsHelpers.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_planDetails.scss
  src/routes/plans.js
  src/views/planDetails.hbs
Labels: Requirement finished 🏁

#5 Hero section
  src/database/DB.sql
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_home.scss
  src/views/index.hbs
Labels: section/component finished 👣

#6 Fix landscape devices carrousel sectio problem 🐛
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/pages/_home.scss
Labels: bug

#7 Anexo de why section y pequeños ajustes estílisticos
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_home.scss
  src/views/index.hbs
Labels: section/component finished 👣

#8 Anexo del footer y pequeños cambios
  src/public/styles/layouts/_footer.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/views/layouts/main.hbs
Labels: section/component finished 👣

#9 Alerts for flash messages finished
  src/public/scripts/_alerts.js
  src/public/styles/layouts/_alerts.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/views/layouts/main.hbs
Labels: section/component finished 👣

#12 Vistas, estilos, mensajes flash, enrutamiento y validación password para signin y signup
  src/controllers/user_controller.js
  src/controllers/users_controller.js
  src/database/keys.js
  src/index.js
  src/libs/helpers.js
  src/libs/passport.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_auth.scss
  src/routes/authentication.js
  src/routes/router.js
  src/routes/user.js
  src/views/auth/signin.hbs
  src/views/auth/signup.hbs
  src/views/layouts/main.hbs
  src/views/partials/message.hbs
  src/views/userViews/dashboard.hbs
Labels: section/component finished 👣

#15 Login validation
  src/public/scripts/auth/signin.js
  src/public/scripts/auth/signup.js
  src/public/scripts/validate.js
  src/public/styles/base/_globals.scss
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/pages/_auth.scss
  src/views/auth/signin.hbs
  src/views/auth/signup.hbs
Labels: section/component finished 👣

#14 Plans crud
  src/controllers/admin_controller.js
  src/public/scripts/plans_confirm_delete.js
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_adminCreatePlan.scss
  src/public/styles/pages/_adminPlans.scss
  src/routes/admin.js
  src/views/adminViews/createPlan.hbs
  src/views/adminViews/editPlan.hbs
  src/views/adminViews/plans.hbs
Labels: Requirement finished 🏁

#17 form__icon position fix 🐛
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
Labels: bug

#18 Plan comments
  src/controllers/plans_controller.js
  src/libs/handlebarsHelpers.js
  src/libs/protect_functions.js
  src/public/scripts/plans_comment_confirm_delete.js
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/pages/_planDetails.scss
  src/routes/plans.js
  src/views/planDetails.hbs
Labels: Requirement finished 🏁

#19 Nav roles and some changes
  src/controllers/users_controller.js
  src/public/images/vectors/explore.png
  src/routes/authentication.js
  src/routes/general_routes.js
  src/views/adminViews/dashboard.hbs
  src/views/layouts/main.hbs
Labels: section/component finished 👣

#21 Update admin dashboard.
  src/views/adminViews/dashboard.hbs
Labels: Little update 🔃

#23 User plans
  .gitignore
  src/controllers/user_controller.js
  src/controllers/users_controller.js
  src/libs/passport.js
  src/libs/protect_functions.js
  src/public/styles/main.css.map
  src/routes/authentication.js
  src/routes/user.js
  src/views/adminViews/plans.hbs
  src/views/planDetails.hbs
  src/views/userViews/dashboard.hbs
  src/views/userViews/userEditplans.hbs
Labels: Requirement finished 🏁

#24 Indluce moment.js for TIMESTAMP conversion
  package-lock.json
  package.json
  src/libs/handlebarsHelpers.js
Labels: bug

#25 card of plans per user modified
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/pages/_userReservations.scss
  src/views/userViews/userEditplans.hbs
Labels: Little update 🔃

#28 Some pages title changed
  src/controllers/plans_controller.js
  src/controllers/user_controller.js
  src/controllers/users_controller.js
Labels: Little update 🔃

#27 Change .input to .form__input
  src/views/auth/signup_admin.hbs
Labels: bug

#26 Flash messages inprovement
  src/controllers/admin_controller.js
  src/libs/passport.js
  src/libs/protect_functions.js
Labels: 📈 IMPROVEMENT

#29 Verify if username already exist
  src/libs/passport.js
Labels: 📈 IMPROVEMENT

#31 Admin signup validation
  src/views/auth/signup_admin.hbs
Labels: 📈 IMPROVEMENT

#30 Useless console.logs deleted
  src/controllers/user_controller.js
  src/libs/helpers.js
Labels: Little update 🔃

#32 Fix some issues 🐛
  src/routes/plans.js
  src/views/adminViews/createPlan.hbs
Labels: bug

#33 SEO improvement
  src/public/scripts/navbar.js
  src/public/styles/layouts/_alerts.scss
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_planDetails.scss
  src/views/adminViews/createPlan.hbs
  src/views/adminViews/dashboard.hbs
  src/views/adminViews/editPlan.hbs
  src/views/adminViews/plans.hbs
  src/views/auth/signin.hbs
  src/views/auth/signup.hbs
  src/views/auth/signup_admin.hbs
  src/views/index.hbs
  src/views/layouts/main.hbs
  src/views/plansNormal.hbs
  src/views/userViews/dashboard.hbs
  src/views/userViews/userEditplans.hbs
Labels: 📈 IMPROVEMENT

#34 Create update account option
  src/controllers/users_controller.js
  src/libs/passport.js
  src/public/images/vectors/update_account.png
  src/public/styles/components/_components.scss
  src/public/styles/main.css
  src/routes/authentication.js
  src/views/auth/edit.hbs
  src/views/userViews/dashboard.hbs
Labels: section/component finished 👣

#35 Fix hero section on landscape mobile devices
  src/public/styles/main.css
  src/public/styles/main.css.map
  src/public/styles/main.scss
  src/public/styles/pages/_home.scss
  src/views/index.hbs
Labels: Little update 🔃
